services:
  db:
    image: postgres:16-alpine
    container_name: membership-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: membership
    ports:
      - "5440:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
