"""add gym_id to membership

Revision ID: d3cc6be95a39
Revises: aa5ff47b32fd
Create Date: 2025-10-09 22:44:50.646250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3cc6be95a39"
down_revision: Union[str, Sequence[str], None] = "aa5ff47b32fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("membership", sa.Column("gym_id", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("membership_id_gym_fkey"), "membership", type_="foreignkey")
    op.create_foreign_key(None, "membership", "gym", ["gym_id"], ["id"])
    op.drop_column("membership", "id_gym")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "membership",
        sa.Column("id_gym", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "membership", type_="foreignkey")
    op.create_foreign_key(
        op.f("membership_id_gym_fkey"), "membership", "gym", ["id_gym"], ["id"]
    )
    op.drop_column("membership", "gym_id")
    # ### end Alembic commands ###
